# Site settings
title: innosam musings
email: innosam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is just me exploring stuff

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: innosams
github_username:  innosam

# Build settings
markdown: kramdown
